from typing import Any

from topic_modeling_streamlit.nlp_utils import get_default_prompt

PRESETS: dict[str, dict[str, Any]] = {
    "Japanese (fast, no-LLM)": {
        "language_option": "Japanese",
        "embedding_model_option": "cl-nagoya/ruri-v3-30m",
        "representation_model_option": ["KeyBERTInspired"],
        "nr_topics_option": 0,
        "tokenizer_dictionary_option": "MeCab/近現代口語小説UniDic",
        "tokenizer_features_option": ["orth"],
        "tokenizer_pos_filter_option": [],
        "surface_filter_option": r"",
        "ngram_range_option": (1, 1),
        "max_df_option": 0.9,
        "chunksize_option": 100,
        "min_chunksize_option": 20,
        "chunks_option": 50,
    },
    "Japanese (full data, LLM)": {
        "language_option": "Japanese",
        "embedding_model_option": "cl-nagoya/ruri-v3-30m",
        "representation_model_option": [
            "local:Qwen/Qwen3-1.7B",
            "KeyBERTInspired",
            "MaximalMarginalRelevance",
            "PartOfSpeech",
        ],
        "prompt_option": get_default_prompt("Japanese"),
        "nr_topics_option": 0,
        "tokenizer_dictionary_option": "MeCab/近現代口語小説UniDic",
        "tokenizer_features_option": ["lemma"],
        "tokenizer_pos_filter_option": [
            "空白",
            "補助記号",
            "記号",
        ],
        "surface_filter_option": r"^[\u3000-\u303f\uff00-\uffef\p{P}]+$",
        "ngram_range_option": (1, 1),
        "max_df_option": 0.9,
        "chunksize_option": 250,
        "min_chunksize_option": 100,
        "chunks_option": 0,
    },
    "Japanese (full data, Sudachi/C+LLM)": {
        "language_option": "Japanese",
        "embedding_model_option": "cl-nagoya/ruri-v3-30m",
        "representation_model_option": [
            "local:Qwen/Qwen3-1.7B",
            "KeyBERTInspired",
            "MaximalMarginalRelevance",
            "PartOfSpeech",
        ],
        "prompt_option": get_default_prompt("Japanese"),
        "nr_topics_option": 0,
        "tokenizer_dictionary_option": "Sudachi/SudachiDict-full/C",
        "tokenizer_features_option": ["lemma"],
        "tokenizer_pos_filter_option": [
            "空白",
            "補助記号",
            "記号",
        ],
        "surface_filter_option": r"^[\u3000-\u303f\uff00-\uffef\p{P}]+$",
        "ngram_range_option": (1, 1),
        "max_df_option": 0.9,
        "chunksize_option": 250,
        "min_chunksize_option": 100,
        "chunks_option": 0,
    },
    "Japanese (full data, Sudachi/C+LLM, 50 topics)": {
        "language_option": "Japanese",
        "embedding_model_option": "cl-nagoya/ruri-v3-30m",
        "representation_model_option": [
            "local:Qwen/Qwen3-1.7B",
            "KeyBERTInspired",
            "MaximalMarginalRelevance",
            "PartOfSpeech",
        ],
        "prompt_option": get_default_prompt("Japanese"),
        "nr_topics_option": 50,
        "tokenizer_dictionary_option": "Sudachi/SudachiDict-full/C",
        "tokenizer_features_option": ["lemma"],
        "tokenizer_pos_filter_option": [
            "空白",
            "補助記号",
            "記号",
        ],
        "surface_filter_option": r"^[\u3000-\u303f\uff00-\uffef\p{P}]+$",
        "ngram_range_option": (1, 1),
        "max_df_option": 0.9,
        "chunksize_option": 250,
        "min_chunksize_option": 100,
        "chunks_option": 0,
    },
    "English (fast, no-LLM)": {
        "language_option": "English",
        "embedding_model_option": "prdev/mini-gte",
        "representation_model_option": ["KeyBERTInspired"],
        "nr_topics_option": 0,
        "tokenizer_dictionary_option": "spaCy/en_core_web_sm",
        "tokenizer_features_option": ["orth"],
        "tokenizer_pos_filter_option": [],
        "surface_filter_option": r"",
        "ngram_range_option": (1, 1),
        "max_df_option": 0.9,
        "chunksize_option": 100,
        "min_chunksize_option": 20,
        "chunks_option": 50,
    },
    "English (full data, LLM labels)": {
        "language_option": "English",
        "embedding_model_option": "prdev/mini-gte",
        "representation_model_option": [
            "local:Qwen/Qwen3-1.7B",
            "KeyBERTInspired",
            "MaximalMarginalRelevance",
            "PartOfSpeech",
        ],
        "prompt_option": get_default_prompt("English"),
        "nr_topics_option": 0,
        "tokenizer_dictionary_option": "spaCy/en_core_web_sm",
        "tokenizer_features_option": ["lemma"],
        "tokenizer_pos_filter_option": [
            "PUNCT",
        ],
        "surface_filter_option": r"^[\u3000-\u303f\uff00-\uffef\p{P}]+$",
        "ngram_range_option": (1, 1),
        "max_df_option": 0.9,
        "chunksize_option": 250,
        "min_chunksize_option": 100,
        "chunks_option": 0,
    },
    "English (full data, LLM labels, 50 topics)": {
        "language_option": "English",
        "embedding_model_option": "prdev/mini-gte",
        "representation_model_option": [
            "local:Qwen/Qwen3-1.7B",
            "KeyBERTInspired",
            "MaximalMarginalRelevance",
            "PartOfSpeech",
        ],
        "prompt_option": get_default_prompt("English"),
        "nr_topics_option": 50,
        "tokenizer_dictionary_option": "spaCy/en_core_web_sm",
        "tokenizer_features_option": ["lemma"],
        "tokenizer_pos_filter_option": [
            "PUNCT",
        ],
        "surface_filter_option": r"^[\u3000-\u303f\uff00-\uffef\p{P}]+$",
        "ngram_range_option": (1, 1),
        "max_df_option": 0.9,
        "chunksize_option": 250,
        "min_chunksize_option": 100,
        "chunks_option": 0,
    },
}

NON_LLM_REPRESENTATION_OPTIONS = [
    "KeyBERTInspired",
    "MaximalMarginalRelevance",
    "PartOfSpeech",
]


LLM_REPRESENTATION_OPTIONS = [
    "local:Qwen/Qwen3-1.7B",
    # "litellm:openrouter/google/gemma-3n-e4b-it:free",  # Does not support system prompt ("Developer instruction")
    "litellm:openrouter/qwen/qwen3-235b-a22b-07-25:free",
    "litellm:openrouter/moonshotai/kimi-k2:free",
    "litellm:gpt-4.1-nano",
    "litellm:bedrock/us.amazon.nova-micro-v1:0",
    "litellm:bedrock/us.amazon.nova-lite-v1:0",
    "litellm:bedrock/us.amazon.nova-pro-v1:0",
    "litellm:bedrock/us.deepseek.r1-v1:0",
]
